### ISSUE TITLE
Force Windows line breaks on cuesheet creation

### ISSUE THREAD

**Issue by bikerspade** [superg/redumper#139]
Cuesheets that are downloaded from the redump website use Windows (CRLF) line breaks.
However, running redumper in a UNIX environment currently produces UNIX (LF) line breaks.

I noticed this when trying to compare cuesheet differences between two different audio disc masterings.
Below are logs from audio CDs dumped with redumper in a UNIX environment:
http://forum.redump.org/topic/54878/audiocd-final-fantasy-xv-original-soundtrack-mergebad-dump/

For consistency, could the cuesheet creation be forced to use CRLF line breaks?

**Comment by superg** [comment]
While technically feasible, it's not the right way. redumper just outputs text lines, line breaks are OS dependent. It is super inconvenient to open windows CRLF files when working in Linux. Seeing LF when dumped on Linux is the expected behavior. User might want to work with these cue sheets (cuetools etc) and that might be broken if I do CRLF.
There is also older mac with CR endings.

The real problem here is that redump.org has to favor some encoding when providing cue zips and I don't see a solution to this.
