### ISSUE TITLE
refine - add a TOC mismatch override option

### ISSUE THREAD

**Issue by superg** [superg/redumper#159]
As some generic drives return mismatching TOC data.

**Comment by ehw** [comment]
Might be unrelated but this issue seems to affect certain DVD(-R?)s brands and even some older Plextors as well, not just strictly generic. Been meaning to reach out to you about it.

I've been working with someone to try and refine some DVDs but for some reason, certain drives are reporting different disc sizes and not all of them are generic, which seems to make redumper think they're not the same disc. For instance, a DVD-R DL in various drives according to isobuster gives me this:

ASUS bluray drive and a 755SA
![image](https://github.com/superg/redumper/assets/885618/10fe4d98-04be-4125-92e2-fbdc0f9a018a)
![image](https://github.com/superg/redumper/assets/885618/6f9e626d-6b0c-4f7f-be3d-641368f3301e)

But in a much older 708A, which I **think** supports DL but maybe certain brands are harder to read than others?

![image](https://github.com/superg/redumper/assets/885618/15c74ee0-d1d5-41fb-8778-19ed196bdf02)


So if an initial dump is done in an ASUS, I can refine in the 755SA. However, if I do an initial dump in a 708A, I can't refine it anything.

For this disc in particular, redumper reports the following:

708A:

> disc structure:
>   layer 0 { recordable }
>     data { LBA: [196608 .. -209585], length: 4172816, hLBA: [0x030000 .. 0xFCCD4F] }
>     data layer 0 last { LBA: 2289503, hLBA: 0x22EF5F }
>     book type: DVD-ROM
>     part version: 6
>     disc size: 120mm
>     maximum rate: not specified
>     layers count: 2
>     track path: opposite
>     linear density: 0.293 um/bit
>     track density: 0.74 um/track
>     BCA: no

ASUS:
> disc structure:
>   layer 0 { recordable }
>     data { LBA: [196608 .. -909251], length: 3473150, hLBA: [0x030000 .. 0xF2203D] }
>     data layer 0 last { LBA: 2289503, hLBA: 0x22EF5F }
>     book type: DVD-R
>     part version: 15
>     disc size: 120mm
>     maximum rate: not specified
>     layers count: 2
>     track path: opposite
>     linear density: 0.293 um/bit
>     track density: 0.74 um/track
>     BCA: no
> 
> layer break: 2092896

[ASUS log](https://github.com/user-attachments/files/15572653/split_second_Xbox_360_debug_review_disc_asus_initial_dump.1.log)
[708A log](https://github.com/user-attachments/files/15572654/split_second_Xbox_360_debug_review_disc.log)
