### ISSUE TITLE
Issues with a CD-I game disc

### ISSUE THREAD

**Issue by Morlit55** [superg/redumper#188]
Namely this one http://redump.org/disc/79065/. 

Dumping normally causes an "unable to establish base LBA" Error. And trying to force offset leads to a "error: data errors detected, unable to continue" string. You can see attached log for details. 

[Foqus.log](https://github.com/user-attachments/files/17174819/Foqus.log)

**Comment by superg** [comment]
The base LBA error is expected as this particular disc mastering is bad.

I see that you tried `split --force-offset=88180 --image-name=foqus` but forgot to add --force-split, that's why it didn't work on manual resplit. Without --force-split it will not let you add padding to inaccessible leadout data needed because of a huge offset.

**Comment by Morlit55** [comment]
I tried that now and yep it worked. 
[Foqus.log](https://github.com/user-attachments/files/17188110/Foqus.log)
